### ISSUE TITLE
Issues on Grep_Iter

### ISSUE THREAD

**Issue by mfeldyriza** [RonenNess/grepfunc#2]
Hi, 

I found this issue when I tried grep_iter
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
~\Anaconda3\lib\site-packages\grepfunc\grepfunc.py in grep_iter(target, pattern, **kwargs)
    234     # done iteration
--> 235     raise StopIteration
    236 

StopIteration: 

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-8-4447fb8c5740> in <module>
      6 
      7 # print all people with first name 'Bob'
----> 8 for POT in  grep_iter(infile, "WPOT_TOTAL2"):
      9     print (POT)

RuntimeError: generator raised StopIteration

It might need to end loop when the codes read the end of the line?

**Comment by xsummusx** [comment]
Ran into the same problem and is due to change in Python in how generators are terminated (I'm not sure in which version of Python this was introduced).  Refer to [PEP 479 -- Change StopIteration handling inside generators ](https://www.python.org/dev/peps/pep-0479/).

I fixed this problem for my needs by editing grepfunc.py, and commenting out line 237.
`    #raise StopIteration`

Find your python cache for grepfunc and delete those files and then you can re-import grepfunc and use.
